version : '3.7'
services:
  jenkins:
    image: jenkins/jenkins:latest
    user: root
    ports:
     - "8080:8080"
     - "50000:50000"
    volumes:
     - "jenkins_home:/var/jenkins_home"
    networks:
     - net
  remote_host:
    image: centos/remote_host
    build:
      context: .
      dockerfile: centos-build-Dockerfile
    networks:
     - net
  db-host:
    image: mysql:8.0.23
    environment:
     - "MYSQL_ROOT_PASSWORD=root"
    volumes:
     - "$PWD/db_data:/var/lib/mysql"
    ports: 
     - "3037:3036"
    networks:
     - net

networks:
  net:
volumes:
  jenkins_home:
