version : '3.7'
services:
  jenkins:
    image: jenkins/docker
    build:
      context: pipeline/prod_env
      dockerfile: prod_jenkins_dockerfile
    user: root
    ports:
     - "8080:8080"
     - "50000:50000"
    volumes:
     - "jenkins_var:/var"
    networks:
     - net
  remote_host:
    image: centos/remote_host
    build:
      context: .
      dockerfile: centos-build-Dockerfile
    ports:
     - "22:22"
    volumes:
     - "remote_host_data:/tmp"
    networks:
     - net
  db-host:
    image: mysql:8.0.23
    environment:
     - "MYSQL_USER=root"
     - "MYSQL_ROOT_PASSWORD=root"
     - "MYSQL_PASSWORD=root"
     - "MYSQL_DATABASE=testdb"
    volumes:
     - "mysql_data:/var/lib/mysql"
     - "mysql_config:/etc/mysql/conf.d"
    ports: 
     - "3037:3036"
    networks:
     - net

networks:
  net:
volumes:
  jenkins_var:
  mysql_data:
  mysql_config:
  remote_host_data:


# The mysql needs to have 2 volumes one for config and the other for data.
# store all persistant data to /tmp directory of 'REMOTE_HOST'
