version : "3"
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:latest
    ports:
     - "8080:8080"
    volumes:
     - "$PWD/jenkins_home:/var/jenkins_home"
    networks:
     - net
  remote_host:
    container-name: remote_host
    image: centos/remote_host
    build:
      context: .
      dockerfile: centos-build-Dockerfile
    networks:
     - net
  db-host:
    container-name: mysql_db
    image: mysql:8.0.23
    environment:
     - "MYSQL_ROOT_PASSWORD=root"
    volumes:
     - "$PWD/db_data:/var/lib/mysql"
    ports: 
     - "3037:3036"
    networks:
     - net

networks:
  net:

