pipeline {
    agent any
    stages {
        stage('Build') {
            steps{
                sh """
                        ./build-java.sh && \
                        ./build-docker-compose.sh
                    """
            }
            
        }
        stage('Test') {
            steps{
                sh("./test-java.sh")
            }
            
        }

        stage('Push') {
            steps{
                sh('./push_docker_java.sh')

            }
        }

        stage('Deploy') {
            steps {
                sh('./deploy.sh')
            }
        }
    }
} 