pipeline {
    agent any

    environment {
        PASS credentials("DOCKER_PASSWD")
    }
    stages {
        stage('Build') {
            steps{
                sh """
                        ./build/build-java.sh && \
                        ./build/build-docker-compose.sh
                    """
            }
            
        }
        stage('Test') {
            steps{
                sh("./test/test-java.sh")
            }
            
        }

        stage('Push') {
            steps{
                sh('./push/push_docker_java.sh')

            }
        }

        stage('Deploy') {
            steps {
                sh('./deploy/deploy.sh')
            }
        }
    }
} 