version : '3.7'
services:
  prod_docker:
    image: docker:latest
    working_dir: /var/workspace 
    ports:
     - "8081:8081"
     - "22:22"
    stdin_open: true
    tty: true
    volumes:
     - "docker_prod_certs_ca:/certs/ca"
     - "docker_prod_certs_client:/certs/client"
     - "docker_prod_ssh:/root/.ssh"
     - "docker_prod_data:/var"
    networks:
     - net
  jenkins:
    image: jenkins/jenkins:latest
    user: root
    ports:
     - "8080:8080"
     - "50000:50000"
    volumes:
     - "jenkins_home:/var/jenkins_home"
    networks:
     - net
  remote_host:
    image: centos/remote_host
    build:
      context: .
      dockerfile: centos-build-Dockerfile
    volumes:
     - "remote_host_data:/tmp"
    networks:
     - net
  db-host:
    image: mysql:8.0.23
    environment:
     - "MYSQL_USER=root"
     - "MYSQL_ROOT_PASSWORD=root"
     - "MYSQL_PASSWORD=root"
     - "MYSQL_DATABASE=testdb"
    volumes:
     - "mysql_data:/var/lib/mysql"
     - "mysql_config:/etc/mysql/conf.d"
    ports: 
     - "3037:3036"
    networks:
     - net

networks:
  net:
volumes:
  jenkins_home:
  mysql_data:
  mysql_config:
  remote_host_data:
  docker_prod_certs_ca:
  docker_prod_certs_client:
  docker_prod_data:
  docker_prod_ssh:

# The mysql needs to have 2 volumes one for config and the other for data.
# store all persistant data to /tmp directory of 'REMOTE_HOST'
